### ISSUE TITLE
老哥，部分缺字补充.txt  有空补充进去，我再补充一批

### ISSUE THREAD

**Issue by gaboolic** [mirtlecn/chaizi-re#3]
之前做墨奇音形 我手工拆了一些

**Comment by mirtlecn** [comment]
稍等，我改下 CI，防止出错

**Comment by mirtlecn** [comment]
里面有几千个（大概）机器没法识别的字符，要手动慢慢改。最近没空

**Comment by mirtlecn** [comment]
非常感谢贡献。

直接粘贴进 radical.txt，然后执行 make 就能自动调整格式和去重（或者执行 python lint.py 也行）。
